### ISSUE TITLE
[Feature] 建议增加根据外部MYSQL配置信息 插入数据源demo链接信息的功能

### ISSUE THREAD

**Issue by zhengkunwang223** [dataease/dataease#4491]
**请描述您的需求或者改进建议.**

使用docker-compose + 外部数据库  启动了simple 的 de，发现数据源中的demo链接信息是 migration 中写死的
能否支持根据配置信息自动生成外部数据库的demo数据源

docker-compose 如下

```
version: '3'
services:
  dataease:
    image: registry.cn-qingdao.aliyuncs.com/dataease/dataease:v1.18.2
    container_name: dataease
    ports:
      - ${PANEL_APP_PORT_HTTP}:8081
    volumes:
      - ./conf:/opt/dataease/conf
      - ./logs:/opt/dataease/logs
      - ./plugins/thirdpart:/opt/dataease/plugins/thirdpart
      - ./data/static-resource:/opt/dataease/data/static-resource
      - ./custom-drivers:/opt/dataease/custom-drivers
      - ./data/custom:/opt/dataease/data/custom
      - ./data/business:/opt/dataease/data/business
    environment:
      PANEL_DB_HOST: ${PANEL_DB_HOST}
      PANEL_DB_PORT: 3306
      PANEL_DB_USER: ${PANEL_DB_USER}
      PANEL_DB_USER_PASSWORD: ${PANEL_DB_USER_PASSWORD}
      PANEL_DB_NAME: ${PANEL_DB_NAME}
    shm_size: 1gb
    networks:
      - 1panel

networks:
  1panel:
    external: true
```

配置文件如下

```
# 数据库配置
spring.datasource.url=jdbc:mysql://${PANEL_DB_HOST}:3306/${PANEL_DB_NAME}?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
spring.datasource.username=${PANEL_DB_USER}
spring.datasource.password=${PANEL_DB_USER_PASSWORD}

#新建用户初始密码
dataease.init_password=DataEase123456
#登录超时时间单位min  如果不设置 默认8小时也就是480
dataease.login_timeout=480

logger.level=INFO

#DE运行模式，可选值有 local、simple、cluster，分别对应 本地模式、精简模式、集群模式
engine_mode=simple
```
