### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by lwx57280** [dataease/dataease#4937]
**安装环境和DataEase 版本**

硬件：8G * 2 运行内存，317G物理磁盘、CPU: 4核
软件：DataEase-v1.18.5
虚拟机：CentOs7

**运行方式(安装包运行 or 源码运行 ?)**

 源码本地离线安装

1、安装配置install.conf已按需修改
```
# 基础配置
## 安装目录
DE_BASE=/home
## Service 端口
DE_PORT=8088
## 部署及运行模式，可选值有 local、simple、cluster，分别对应 本地模式、精简模式、集群模式
DE_ENGINE_MODE=simple
## docker 网段设置
DE_DOCKER_SUBNET=172.33.0.0/16
## docker 网关 IP
DE_DOCKER_GATEWAY=172.33.0.1
## Apache Doris FE IP (外部 Doris 此参数无效)
DE_DORIS_FE_IP=172.33.0.198
## Apache Doris BE IP (外部 Doris 此参数无效)
DE_DORIS_BE_IP=172.33.0.199
## 登录超时时间，单位min。如果不设置则默认8小时，也就是480
DE_LOGIN_TIMEOUT=480

# 数据库配置
## 是否使用外部数据库
DE_EXTERNAL_MYSQL=false
## 数据库地址（默认mysql，之前如果用docker安装过mysql建议修改）
DE_MYSQL_HOST=mysql-de
## 数据库端口
DE_MYSQL_PORT=3306
## DataEase 数据库库名
DE_MYSQL_DB=dataease
## 数据库用户名
DE_MYSQL_USER=yxw01
## 数据库密码
DE_MYSQL_PASSWORD=yxw@123!

# Apache Doris 配置
## 是否使用外部 Apache Doris
DE_EXTERNAL_DORIS=false
## Doris 地址
DE_DORIS_HOST=doris-fe
## Doris 查询连接端口
DE_DORIS_PORT=9030
## Doris http端口
DE_DORIS_HTTPPORT=8030
## Doris 数据库名称
DE_DORIS_DB=dataease
## Doris 用户名
DE_DORIS_USER=root
## Doris 密码
DE_DORIS_PASSWORD=Password123@doris

# Kettle 配置
## 是否使用外部 Kettle - (目前还不支持外部Kettle，除非不需运行Kettle，否则请不要修改此参数)
DE_EXTERNAL_KETTLE=false
## Kettle 服务器地址
DE_CARTE_HOST=kettle
## Kettle 访问端口
DE_CARTE_PORT=18080
## Kettle 用户名
DE_CARTE_USER=cluster
## Kettle 密码
DE_CARTE_PASSWORD=cluster
```
2、环境变量.env 文件已按需修改
```
DE_DORIS_PASSWORD=Password123@doris
DE_CARTE_PASSWORD=cluster
DE_MYSQL_PASSWORD=yxw@123!
DE_EXTERNAL_DORIS=false
DE_DORIS_HTTPPORT=8030
DE_PORT=80
DE_EXTERNAL_MYSQL=false
DE_DORIS_PORT=9030
DE_CARTE_PORT=18080
DE_MYSQL_USER=yxw01
DE_LOGIN_TIMEOUT=480
DE_DOCKER_GATEWAY=172.33.0.1
DE_DORIS_FE_IP=172.33.0.198
DE_MYSQL_HOST=192.168.11.36
DE_DORIS_BE_IP=172.33.0.199
DE_MYSQL_PORT=3306
DE_DORIS_HOST=doris-fe
DE_CARTE_HOST=kettle
DE_EXTERNAL_KETTLE=false
DE_MYSQL_DB=dataease
DE_BASE=/home
DE_DOCKER_SUBNET=172.33.0.0/16
DE_DORIS_USER=root
DE_CARTE_USER=cluster
DE_ENGINE_MODE=local
DE_DORIS_DB=dataease

```
3、docker-compose.yml 文件已按需修改
```
version: '2.1'
services:

  dataease:
    image: registry.cn-qingdao.aliyuncs.com/dataease/dataease:v1.18.5
    container_name: dataease
    ports:
      - ${DE_PORT}:8081
    mem_limit: 4096m
    volumes:
      - ${DE_BASE}/dataease/conf:/home/dataease/conf
      - ${DE_BASE}/dataease/logs:/home/dataease/logs
      - ${DE_BASE}/dataease/plugins/thirdpart:/home/dataease/plugins/thirdpart
      - ${DE_BASE}/dataease/data/kettle:/home/dataease/data/kettle
      - ${DE_BASE}/dataease/data/static-resource:/home/dataease/data/static-resource
      - ${DE_BASE}/dataease/custom-drivers:/home/dataease/custom-drivers
      - ${DE_BASE}/dataease/data/custom:/home/dataease/data/custom
      - ${DE_BASE}/dataease/data/business:/home/dataease/data/business
      - ${DE_BASE}/dataease/data/ehcache:/home/dataease/data/ehcache
    shm_size: 1gb
    depends_on:
     # 如果之前使用Docker安装过mysql，修改名称
      mysql-de:
        condition: service_healthy
    networks:
      - dataease-network

networks:
  dataease-network:
    driver: bridge
    ipam:
      driver: default
      # 默认网段配置可能会冲突，建议修改
      config:
        - subnet: 172.33.0.0/16
          gateway: 172.33.0.1

```
4、docker-compose-kettle-doris.yml文件已按需修改
```
services:

  doris-fe:
    image: registry.cn-qingdao.aliyuncs.com/dataease/doris:v1.1.0-0704
    container_name: doris-fe
    environment:
      - DORIS_ROLE=fe-leader
    volumes:
      - ${DE_BASE}/dataease/data/fe:/home/doris/fe/doris-meta
      - ${DE_BASE}/dataease/logs/fe:/home/doris/fe/log
      - ${DE_BASE}/dataease/conf/fe.conf:/home/doris/fe/conf/fe.conf
      - ${DE_BASE}/dataease/bin/doris:/docker-entrypoint-initdb.d/
    networks:
      dataease-network :
        # 修改为33网段防止冲突
        ipv4_address: 172.33.0.198
    restart: always
    depends_on:
      doris-be:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS 127.0.0.1:8030 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3

  doris-be:
    image: registry.cn-qingdao.aliyuncs.com/dataease/doris:v1.1.0-0704
    container_name: doris-be
    environment:
      - DORIS_ROLE=be
    volumes:
      - ${DE_BASE}/dataease/data/be:/home/doris/be/storage
      - ${DE_BASE}/dataease/logs/be:/home/doris/be/log
      - ${DE_BASE}/dataease/conf/be.conf:/home/doris/be/conf/be.conf
    networks:
    # 修改为33网段防止冲突
      dataease-network :
        ipv4_address: 172.33.0.198
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS 127.0.0.1:8040 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3

```
5、docker-compose-mysql.yml文件已按需修改
```
version: '2.1'
services:

  mysql-de:
    image: registry.cn-qingdao.aliyuncs.com/dataease/mysql:5.7.39
    # 之前使用Docker安装过mysql，需要修改容器名称
    container_name: mysql-de
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u${DE_MYSQL_USER}", "-p${DE_MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 10
    env_file:
      - ${DE_BASE}/dataease/conf/mysql.env
    ports:
      - ${DE_MYSQL_PORT}:3306
    volumes:
      - ${DE_BASE}/dataease/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ${DE_BASE}/dataease/bin/mysql:/docker-entrypoint-initdb.d/
      - ${DE_BASE}/dataease/data/mysql:/var/lib/mysql
    networks:
      - dataease-network
                                                                                                                 
```

**Bug 描述**

各项配置文件已按需进行修改后一切准备就绪，直接运行安装目录下的install.sh 文件进行安装时，**初次安装一直报错
ERROR: for doris-fe  Cannot start service doris-fe: Address already in use** ；接下来就是进入循环启动；因此我不确定这是否时bug还是因为环境配置哪里需要做修改

**Bug 重现步骤(有截图更好)**
1. 执行./install.sh 安装报错
<img width="432" alt="20230331120257" src="https://user-images.githubusercontent.com/33561119/229019834-890d930e-4c39-4d3e-92f3-48ecadf106a1.png">

<img width="1125" alt="20230331120751" src="https://user-images.githubusercontent.com/33561119/229020433-61fd135c-901d-40b9-8e32-230cfce10649.png">

2.安装生成日志文件install.log
```
[root@node3 dataease-v1.18.5-online]# cat install.log 

*******************************************************

 当前部署模式为 local，如需切换模式，
 请修改 /home/dataease/.env 中的 DE_ENGINE_MODE 变量后，
 重新执行 bash install.sh 即可

*******************************************************

======================= 开始安装 =======================
[DATAEASE Log]: 拷贝配置文件模板文件  -> /home/dataease/conf 
[DATAEASE Log]: 根据安装配置参数调整配置文件 
[DATAEASE Log]: 检测到 Docker 已安装，跳过安装步骤 
[DATAEASE Log]: 启动 Docker  
Redirecting to /bin/systemctl start docker.service
[DATAEASE Log]: 检测到 Docker Compose 已安装，跳过安装步骤 
[DATAEASE Log]: 拉取镜像 
[DATAEASE Log]: 配置 dataease Service 
[DATAEASE Log]: 防火墙未开启，忽略端口开放 
[DATAEASE Log]: 启动服务 


DataEase 服务状态 : 正在启动
DataEase 服务状态 : 正在启动
DataEase 服务状态 : 正在启动
DataEase 服务状态 : 正在启动

```

3.
