### ISSUE TITLE
[Bug]连接Kylin数据源报错java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter

### ISSUE THREAD

**Issue by jeffqiu1989** [dataease/dataease#5877]
**DataEase 版本**
registry.cn-qingdao.aliyuncs.com/dataease/dataease   v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
docker-compose.yaml
```
name: "bi"

services:
  dataease:
    image: registry.cn-qingdao.aliyuncs.com/dataease/dataease:v1.18.9
    ports:
      - 8081:8081
    mem_limit: 4096m
    volumes:
      - ./dataease.properties:/opt/dataease/conf/dataease.properties
      - ./logs:/opt/dataease/logs
    shm_size: 1gb
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - dataease-network
  mysql:
    image: mysql:5.7
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=dataease
    ports:
      - 3306:3306
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_general_ci",
        "--skip-character-set-client-handshake"
      ]
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - dataease-network

networks:
  dataease-network:

volumes:
  data-mysql:
```

dataease.properties
```
# 数据库配置
spring.datasource.url=jdbc:mysql://mysql:3306/dataease?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
spring.datasource.username=root
spring.datasource.password=123456

#新建用户初始密码
dataease.init_password=123456
#登录超时时间单位min  如果不设置 默认8小时也就是480
dataease.login_timeout=30
logger.level=INFO
#DE运行模式，可选值有 local、simple、cluster，分别对应 本地模式、精简模式、集群模式
engine_mode=simple
```

my.cnf
```
[mysqld]
datadir=/var/lib/mysql

default-storage-engine=INNODB
character_set_server=utf8
lower_case_table_names=1
table_open_cache=128
max_connections=2000
max_connect_errors=6000
innodb_file_per_table=1
innodb_buffer_pool_size=1G
max_allowed_packet=64M
transaction_isolation=READ-COMMITTED
innodb_flush_method=O_DIRECT
innodb_lock_wait_timeout=1800
innodb_flush_log_at_trx_commit=0
sync_binlog=0
group_concat_max_len=1024000

sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

skip-name-resolve

[mysql]
default-character-set=utf8

[mysql.server]
default-character-set=utf8
```

**jdk版本**
openjdk version "11.0.20" 2023-07-18
OpenJDK Runtime Environment (build 11.0.20+8-alpine-r2)
OpenJDK 64-Bit Server VM (build 11.0.20+8-alpine-r2, mixed mode)

**Bug 描述**
配置kylin数据源，校验测试报错：
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
这是因为docker image中使用jdk 11，去掉了一些旧的jar包
`JAXB API是java EE 的API，因此在java SE 9.0 中不再包含这个 Jar 包。
java 9 中引入了模块的概念，默认情况下，Java SE中将不再包含java EE 的Jar包
而在 java 6/7 / 8 时关于这个API 都是捆绑在一起的`

**解决方法**
引入缺少的依赖
```
<dependency>
        <groupId>javax.xml.bind</groupId>
        <artifactId>jaxb-api</artifactId>
        <version>2.3.0</version>
    </dependency>
    <dependency>
        <groupId>com.sun.xml.bind</groupId>
        <artifactId>jaxb-impl</artifactId>
        <version>2.3.0</version>
    </dependency>
    <dependency>
        <groupId>com.sun.xml.bind</groupId>
        <artifactId>jaxb-core</artifactId>
        <version>2.3.0</version>
    </dependency>
    <dependency>
        <groupId>javax.activation</groupId>
        <artifactId>activation</artifactId>
        <version>1.1.1</version>
    </dependency>
```
