### ISSUE TITLE
v2.1.0 版本安装后默认账号密码是什么？

### ISSUE THREAD

**Issue by wumindc** [dataease/dataease#7449]
**请描述您的问题.**
使用 docker-compose 在线安装的 dataease
```yaml
version: '2.1'
services:
  dataease:
    image: registry.cn-qingdao.aliyuncs.com/dataease/dataease:v2.1.0
    container_name: dataease
    ports:
      - 8100:8100
    volumes:
      - ./dataease2.0/conf:/opt/apps/config
      - ./dataease2.0/logs:/opt/dataease2.0/logs
      - ./dataease2.0/data/static-resource:/opt/dataease2.0/data/static-resource
      - ./dataease2.0/cache:/opt/dataease2.0/cache
      - ./dataease2.0/data/geo:/opt/dataease2.0/data/geo
    networks:
      - dataease-network

networks:
  dataease-network:
```

然后启动起来后可以访问了，看数据库也自动生成了，然后也可以访问。

但是账号密码不知道是什么，搜索了一遍和官网都没有找到呢，请问下去哪里获取账号密码，看数据库表好像有一张 per_user 表，但是密码也是不知道的

期望：告知去哪里获取账号密码
